version: "3.6"

services:
  php:
    build: ./docker
    restart: unless-stopped
    volumes:
      - ./:/var/www/returns-staging-deployer
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa:/home/www-data/.ssh/id_rsa
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
      - ~/.ssh/known_hosts:/home/www-data/.ssh/known_hosts
    working_dir: /var/www/returns-staging-deployer
    environment:
      PHP_IDE_CONFIG: "serverName=returns-staging-deployer"
    expose:
      - 9000
      - 9003

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www/returns-staging-deployer
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  mysql:
    image: mysql:latest
    restart: unless-stopped
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - 3333:3306
    volumes:
      - ./storage/mysql-data:/var/lib/mysql
      - ./storage/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "returns_staging_secret"
      MYSQL_DATABASE: "returns_staging_deployer"
      MYSQL_USER: "returns_staging_deployer"
      MYSQL_PASSWORD: "returns_staging_secret"
